---
title: "Final Project, Task 1: Description of paper and model"
author: "Demorest, Lemire and Wilson"

output:
  pdf_document: default
  html_document: default
fontsize: 12 pt
---

<!-- By the end of the day 11/12/21, please submit a copy of the pdf of the paper your group will be using for the final project to the _project-assignmnet1_ dropbox. Additionally, please submit a single document for your group that addresses the following:  -->

__1. A brief description of the background motivation of your chosen article and a _single_ research question you will choose to investigate that was presented in the paper. Note that your article may address more than 1 question but I want you to focus on just 1 for this project.__

__Chosen Paper:__ Our chosen paper is *Relative age and birthplace effect in Japanese professional sports: a quantitative evaluation using a Bayesian hierarchical Poisson model* by Hideaki Ishigami (published in the Journal of Sports Sciences in 2016).

__Background Motivation:__ The Relative Age Effect (RAE) is a term used to describe how those born early in the academic year tend to have an advantage both athletically and academically. An earlier birth is typically associated with increased physical ability and this advantage may occur because those who are older are typically more physically, emotionally or cognitively developed than those who are younger. Much research has been done to look at the relative age effect in athletes in North America and Europe. However this paper and our analysis extends this research to include Asian countries. This is an important step in geographically extending the scope of inference regarding the relative age effect. Additionally this paper and our analyses allow the magnitude of relative age to be quantified. In contrast many other analyses have simply stated whether an effect is statistically significant, for example using a $\chi^2$ test. Although it is beyond the scope of this paper, these results impact parents' decisions surrounding red shirting and informs public understanding of factors influencing success in athletics (particularly professional athletics). 

<!-- could also add how this work quantifies the impact rather than just noticing it. they highlight that in the intro too -->

<!-- also it's kind of funnt i'm saying the purpose of our study is to look at the effect in asian countries because we're simulating our data not actually using their data haha
-->
__Single Research Question:__ What is the relative age effect on soccer players in Japan between the ages of 23 and 25?

__2. A brief description of the methods used by the authors of your paper to address the question of interest you are focusing on.__

### Data

The participants in the original study were professional baseball and soccer players, but we will focus only on professional soccer. The Japan Professional Football League (J. League) consists of 40 teams, representing a total of 1013 players registered in the 2012 season and we will focus on players between the ages of 23 and 25, for a total of 227. 

The school year in Japan begins April and ends on March of the following calendar year, which corresponds with the competitive season of most professional sports. Birth date was treated as monthly data and because school year and competitive season both begin in April in Japan, relative age was coded as 0 (April) to 11 (March).

An athlete's birthplace is defined as the prefecture the player was born in. A prefecture is a first-order administrative district in Japan, and there are 47 prefectures in total.

The author's model includes the total number of male children born in each month as an offset term, which is a variable whose coefficient is fixed at one. The variable in the estimated equation is the total number of male births over the years when the sampled players were born.

### Methods

Becoming a soccer player can be seen as an “event”, and a number of them can be regarded as
a “count of events”. Thus, the author applied a Bayesian hierarchical Poisson regression model.


__3. The full probability model used in the paper written out in mathematical notation. That is, all likelihood and prior components.__

### Likelihoood
Our data are denoted by $y_{i}$ which represents the number of professional sports players. The subscript $i$ indicates birth month. Our likelihood, or data generating mechanism, is described by the following distribution:

$$y_{i} \sim \text{Poisson}(\lambda_{i}) \text{ for months } i=1,\dots,12;$$
  <!-- note: If we're only doing soccer I think we only need i, because j is location (for population and weather) and k is for sport... whops nevermind. i'm going back in our convo and seeing that we decided we'll include all three covariates.... we can always change later I'm sure - if we need to -->
  
### Priors
__need to add stuff about offset term i.e. theta and priors are for alpha and beta__

Our priors on $\lambda_{i}$ are defined by the exponential relationship below where $\theta_{i}$ is the total number of male children born in month $i$ with an intercept term $\alpha$. $RA_i$ is the relative age of those born in month $i$, while the coefficient $\beta$ measures the relative age effect (RAE). For example, April would be month 1, with $RA_1 = 0$. The exponential term gives the probability of becoming a professional soccer player.

$$\lambda_{i} = \theta_{i}exp \Bigg \{\alpha +\beta RA_i \Bigg \}$$

### Prior
The authors found the posterior estimate for $\beta|y$ to be $\beta|y \sim \text{Normal}(-0.0934, 0.214^2)$ which we will use as our prior.

We did not see an updated posterior for $\alpha$ so we assume the prior in the paper where 
$\alpha \sim \text{Normal}(\mu, \sigma^2)$ where $\mu \sim \text{Normal}(0,100^2)$ and $\sigma^2 \sim \text{Uniform}(0,100)$. 

__Question for Katie:__ We are confused by the posteriors being on (what seems like) hyperparameters. Are these two "layers" of hyperparameters because our initial model was a two layer hierarchical model? (i.e. random effects varying by month, $i$, and random effects varying by location, $j$, which we excluded). The "two layers" we're seeing are: hyperparameters $\alpha$ and $\beta$ and (hyper)-hyperparameters $\mu$ and $\sigma^2$. Can you help clarify? 

<!-- # Introduction  -->

<!-- The Relative Age Effect (RAE) is a term used to describe how those born early in the academic year tend to have an advantage both athletically and academically. An earlier birth is typically associated with increased physical ability and this advantage may occur because those who are older are typically more physically, emotionally or cognitively developed than those who are younger. Additionally, individuals born earlier in the year may be more likely to persevere in sports since they are able to actively dominate in physical activities and key performance measures. This suggests that as time goes on, those who are less mature drop out of sports as they are not as successful, motivated, or fulfilled by the experience in their younger years of competition, contributing further to their underperformance. -->

<!-- In the paper *Relative age and birthplace effect in Japanese professional sports: a quantitative evaluation using a Bayesian hierarchical Poisson model*, Hideaki Ishigami explores the effect sizes of the relative age and birthplace of becoming a professional athlete for two of the most popular sports in Japan, soccer and baseball. Previous studies suggest that where an athlete was born and developed is another important factor for determining the likelihood of becoming an elite athlete. In Japan, for example, "northern areas may receive, on average, over 100 snow days per year, whereas in the southern areas there are few to no snow days" [@RAE]. As soccer and baseball are not typically played in snow, an athlete's birthplace may have an effect on their athletic development. -->


<!-- # Code Appendix -->


<!-- # References -->


